name: Fetch Zotero

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  zotero:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Fetch Zotero publications
        run: python scripts/zotero.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: [Workflow] Update publications from Zotero
          file_pattern: _data/*